# Generated by Django 5.0.6 on 2024-07-23 10:07

import AWSUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes', validators=[AWSUser.models.validate_pdf_file]),
        ),
    ]
