# Generated by Django 5.0.6 on 2024-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
