# Generated by Django 5.0.6 on 2024-07-23 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_awsblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsblog',
            name='blog_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
